### ISSUE TITLE
Blank for translation

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/inhs-insects#1]
@jhpoelen would this work? The meaning would be "if blank" use parasiteOf

![Screen Shot 2020-07-08 at 10 23 44 AM](https://user-images.githubusercontent.com/1044474/86950742-6616f800-c105-11ea-95ea-6450dac90346.png)

**Comment by jhpoelen** [comment]
I like your idea to map "blank" to default interaction types. 

Currently, only explicit, non-blank, mappings will be performed.

What would  you expect to happen if multiple "blank" mappings are found?

**Comment by seltmann** [comment]
They would all go to parasiteOf based on this translation table.

Right now, a translation table is or all records in a repository, but it would be good to be able to specify based on some criteria.

I assume all black mappings are mapped to http://purl.obolibrary.org/obo/RO_0002437

**Comment by jhpoelen** [comment]
Thanks for clarifying. 

What about when two blank mappings are found? Let's say:


provided_interaction_type_label | provided_interaction_type_id | mapped_to_interaction_type_label | mapped_to_interaction_type_id
-- | -- | -- | --
Host of |   | hostOf | http://purl.obolibrary.org/obo/RO_0002453
Parasite |   | hasParasite | http://purl.obolibrary.org/obo/RO_0002445
Pollinating |   | pollinates | http://purl.obolibrary.org/obo/RO_0002455
Predator |   | preyedUponBy | http://purl.obolibrary.org/obo/RO_0002458
Prey |   | preysOn | http://purl.obolibrary.org/obo/RO_0002439
Reared from |   | hasHost | http://purl.obolibrary.org/obo/RO_0002454
Parasite of |   | parasiteOf | http://purl.obolibrary.org/obo/RO_0002444
Host |   | hasHost | http://purl.obolibrary.org/obo/RO_0002454
  |   | parasiteOf | http://purl.obolibrary.org/obo/RO_0002444
  |   | preysOn | http://purl.obolibrary.org/obo/RO_0002439

where two blank mappings are defined.  

How would you expect default interactions to be mapped in this case?

**Comment by jhpoelen** [comment]
Also, I like you idea of adding more criteria for the mapping.

Is the example below (with added ```provided_source_taxon_class_name``` something along these lines? 


provided_interaction_type_label | provided_interaction_type_id | provided_source_taxon_class_name | mapped_to_interaction_type_label | mapped_to_interaction_type_id
-- | -- | -- | -- | --
Parasite of |   |   | parasiteOf | http://purl.obolibrary.org/obo/RO_0002444
Host |   |   | hasHost | http://purl.obolibrary.org/obo/RO_0002454
  |   |   | parasiteOf | http://purl.obolibrary.org/obo/RO_0002444
  |   | Mammalia | preysOn | http://purl.obolibrary.org/obo/RO_0002439

**Comment by seltmann** [comment]
Yes! That would be a perfect solution. Maybe by class (or other higher taxonomy) or by record range.

**Comment by jhpoelen** [comment]
@seltmann what do you mean by record range? Collection id? Can you provide an example?

**Comment by seltmann** [comment]
occurrenceID  or catalogNumber is what I was thinking

**Comment by jhpoelen** [comment]
So, when matching occurrence ids starting with, let's say, ```FMNH``` you'd have something like the example below?

provided_interaction_type_label | provided_interaction_type_id | provided_source_occurrence_id | mapped_to_interaction_type_label | mapped_to_interaction_type_id
-- | -- | -- | -- | --
| Parasite of |   |   | parasiteOf | http://purl.obolibrary.org/obo/RO_0002444
| Host |   |   | hasHost | http://purl.obolibrary.org/obo/RO_0002454
 | |   |   | parasiteOf | http://purl.obolibrary.org/obo/RO_0002444
 | |   | ```FMNH.*``` | preysOn | http://purl.obolibrary.org/obo/RO_0002439

**Comment by jhpoelen** [comment]
@seltmann in Elton v0.10.1, I've implement support for a "blank" interaction mapping.  In addition,  if custom mappings are available, they add new, or override existing, mappings. Previously, a custom mapping would disable the default mappings (aka factory settings) altogether. 

After the upgrade to 0.10.1, I ran a review and found https://travis-ci.com/github/globalbioticinteractions/inhs-insects/jobs/359373417#L210 :

```
Reviewing [https://raw.githubusercontent.com/globalbioticinteractions/inhs-insects/master] using Elton version [0.10.1].

updating [local]... done.
creating review [local]... done.

Review of [globalbioticinteractions/inhs-insects] included:
  - 12744 interaction(s)
  - 139 note(s)
  - 15336 info(s)

[globalbioticinteractions/inhs-insects] has 139 reviewer note(s):
    139 target taxon name missing
```

I hope this addresses your concern re: blank mappings. I'll add a separate issue for the enhanced mapping features (e.g., using occurrenceIds or other contextual information to enable mappings).

**Comment by jhpoelen** [comment]
For advanced feature suggested earlier, see https://github.com/globalbioticinteractions/globalbioticinteractions/issues/522 . 

@seltmann please confirm the original issue has been addressed by closing this issue.
